/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

/**
 *
 * @author m salman alfarisi
 */
public class Suhu extends javax.swing.JFrame {

    /**
     * Creates new form Suhu
     */
    public Suhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        warning = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        Output = new javax.swing.JComboBox<>();
        panelin = new javax.swing.JLabel();
        panelout = new javax.swing.JLabel();
        teksin = new javax.swing.JTextField();
        teksout = new javax.swing.JTextField();
        btnkonversi2 = new javax.swing.JButton();
        Input = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Konverter Suhu");
        setResizable(false);
        setSize(new java.awt.Dimension(380, 260));
        setType(java.awt.Window.Type.POPUP);

        jLabel1.setText("Pilihan");

        Output.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fahrenheit", "Celcius", "Reamur", "Kelvin" }));
        Output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutputActionPerformed(evt);
            }
        });

        panelin.setText("Input Cekcius:");

        panelout.setText("Output Fahrenheit: ");

        btnkonversi2.setText("Konversi");
        btnkonversi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkonversi2ActionPerformed(evt);
            }
        });

        Input.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Kelvin", "Reamur" }));
        Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(172, 172, 172))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelout)
                            .addComponent(panelin, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teksin, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teksout, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnkonversi2)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panelin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teksin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelout, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(teksout))
                .addGap(18, 18, 18)
                .addComponent(btnkonversi2)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutputActionPerformed
        // TODO add your handling code here:
        if(Output.getSelectedItem()=="Celcius"){
            panelout.setText("Output Celcius:");
        }
        if(Output.getSelectedItem()=="Fahrenheit"){
            panelout.setText("Output Fahrenheit:");
        }
        if(Output.getSelectedItem()=="Reamur"){
            panelout.setText("Output Reamur:");
        }
        if(Output.getSelectedItem()=="Kelvin"){
            panelout.setText("Output Kelvin:");
        }
    }//GEN-LAST:event_OutputActionPerformed

    private void btnkonversi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkonversi2ActionPerformed
        // TODO add your handling code here:
        try{
            //hexa
            if(Input.getSelectedItem()=="Celcius"){
                if(Output.getSelectedItem()=="Fahrenheit"){
                    double t=Double.parseDouble(teksin.getText());
                    double suhu=(t*1.8)+32;
                    teksout.setText(String.valueOf(suhu)+"°");
                }
                else if(Output.getSelectedItem()=="Reamur"){
                    double t=Double.parseDouble(teksin.getText());
                    double suhu=0.8*t;
                    teksout.setText(String.valueOf(suhu)+"°");
                }
                else if(Output.getSelectedItem()=="Kelvin"){
                    double t=Double.parseDouble(teksin.getText());
                    double suhu=273.15+t;
                    teksout.setText(String.valueOf(suhu)+"°");
                }
                else{
                    warning.showMessageDialog(null,"masukkan pilihan/angka yang benar");
                }
            }
            else if(Input.getSelectedItem()=="Kelvin"){
                if(Output.getSelectedItem()=="Fahrenheit"){
                    double t=Double.parseDouble(teksin.getText());
                    double suhu=((t-273.15)*1.8)+32;
                    teksout.setText(String.valueOf(suhu)+"°");
                }
                else if(Output.getSelectedItem()=="Reamur"){
                    double t=Double.parseDouble(teksin.getText());
                    double suhu=0.8*(t-273);
                    teksout.setText(String.valueOf(suhu)+"°");
                }
                else if(Output.getSelectedItem()=="Celcius"){
                    double t=Double.parseDouble(teksin.getText());
                    double suhu=t-273.15;
                    teksout.setText(String.valueOf(suhu)+"°");
                }
                else{
                    warning.showMessageDialog(null,"masukkan input yang benar");
                }
            }
            else if(Input.getSelectedItem()=="Fahrenheit"){
                if(Output.getSelectedItem()=="Kelvin"){
                    double t=Double.parseDouble(teksin.getText());
                    double suhu=((t-32)*1.8)+273.15;
                    teksout.setText(String.valueOf(suhu)+"°");
                }
                else if(Output.getSelectedItem()=="Reamur"){
                    double t=Double.parseDouble(teksin.getText());
                    double suhu=0.444*(t-32);
                    teksout.setText(String.valueOf(suhu)+"°");
                }
                else if(Output.getSelectedItem()=="Celcius"){
                    double t=Double.parseDouble(teksin.getText());
                    double suhu=t-0.556*(t-32);
                    teksout.setText(String.valueOf(suhu)+"°");
                }
                else{
                    warning.showMessageDialog(null,"masukkan input yang benar");
                }
            }
            else if(Input.getSelectedItem()=="Reamur"){
                if(Output.getSelectedItem()=="Fahrenheit"){
                    double t=Double.parseDouble(teksin.getText());
                    double suhu=(2.25*t)+32;
                    teksout.setText(String.valueOf(suhu)+"°");
                }
                else if(Output.getSelectedItem()=="Kelvin"){
                    double t=Double.parseDouble(teksin.getText());
                    double suhu=(1.25*t)+273.15;
                    teksout.setText(String.valueOf(suhu)+"°");
                }
                else if(Output.getSelectedItem()=="Celcius"){
                    double t=Double.parseDouble(teksin.getText());
                    double suhu=1.25*t;
                    teksout.setText(String.valueOf(suhu)+"°");
                }
                else{
                    warning.showMessageDialog(null,"masukkan input yang benar");
                }
            }
        }catch(NumberFormatException ex){
            warning.showMessageDialog(null,"masukkan input yang benar");
        }
    }//GEN-LAST:event_btnkonversi2ActionPerformed

    private void InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputActionPerformed
        // TODO add your handling code here:
        if(Input.getSelectedItem()=="Celcius"){
            panelin.setText("Input Celcius:");
        }
        if(Input.getSelectedItem()=="Fahrenheit"){
            panelin.setText("Input Fahrenheit:");
        }
        if(Input.getSelectedItem()=="Reamur"){
            panelin.setText("Input Reamur:");
        }
        if(Input.getSelectedItem()=="Kelvin"){
            panelin.setText("Input Kelvin:");
        }
    }//GEN-LAST:event_InputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Suhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Input;
    private javax.swing.JComboBox<String> Output;
    private javax.swing.JButton btnkonversi2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel panelin;
    private javax.swing.JLabel panelout;
    private javax.swing.JTextField teksin;
    private javax.swing.JTextField teksout;
    private javax.swing.JOptionPane warning;
    // End of variables declaration//GEN-END:variables
}
