/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

import java.text.DecimalFormat;

/**
 *
 * @author m salman alfarisi
 */
public class Uang extends javax.swing.JFrame {

    /**
     * Creates new form Uang
     */
    public Uang() {
        initComponents();
    }

    double usd=0.0000701;
    double rm=0.0002869;
    double euro=0.0000574;
    double sgd=0.0000926;
    
    DecimalFormat d=new DecimalFormat("#.##");
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        warning = new javax.swing.JOptionPane();
        panelpilihan = new javax.swing.JLabel();
        Input = new javax.swing.JComboBox<>();
        Output = new javax.swing.JComboBox<>();
        panelin = new javax.swing.JLabel();
        teksin = new javax.swing.JTextField();
        panelout = new javax.swing.JLabel();
        teksout = new javax.swing.JTextField();
        btnkonversi3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Konversi Mata Uang");
        setSize(new java.awt.Dimension(380, 260));
        setType(java.awt.Window.Type.POPUP);

        panelpilihan.setText("Pilihan");

        Input.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rp", "USD", "Euro", "SGD", "RM" }));
        Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputActionPerformed(evt);
            }
        });

        Output.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "Euro", "SGD", "RM", "Rp" }));
        Output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutputActionPerformed(evt);
            }
        });

        panelin.setText("Input Rupiah:");

        panelout.setText("Output Dollar Amerika:");

        btnkonversi3.setText("Konversi");
        btnkonversi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkonversi3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelpilihan)
                .addGap(172, 172, 172))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnkonversi3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelout, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(teksout, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelin, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(teksin, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelpilihan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panelin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teksin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelout, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(teksout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnkonversi3)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputActionPerformed
        // TODO add your handling code here:
        if(Input.getSelectedItem()=="Rp"){
            panelin.setText("Input Rupiah:");
        }
        if(Input.getSelectedItem()=="USD"){
            panelin.setText("Input Dollar Amerika:");
        }
        if(Input.getSelectedItem()=="Euro"){
            panelin.setText("Input Euro:");
        }
        if(Input.getSelectedItem()=="SGD"){
            panelin.setText("Input Dollar Singapura:");
        }
        if(Input.getSelectedItem()=="RM"){
            panelin.setText("Input Ringgit Malaysia:");
        }
    }//GEN-LAST:event_InputActionPerformed

    private void OutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutputActionPerformed
        // TODO add your handling code here:
        if(Output.getSelectedItem()=="Rp"){
            panelout.setText("Output Rupiah:");
        }
        if(Output.getSelectedItem()=="USD"){
            panelout.setText("Output Dollar Amerika:");
        }
        if(Output.getSelectedItem()=="Euro"){
            panelout.setText("Output Euro:");
        }
        if(Output.getSelectedItem()=="SGD"){
            panelout.setText("Output Dollar Singapura:");
        }
        if(Output.getSelectedItem()=="RM"){
            panelout.setText("Output Ringgit Malaysia:");
        }
    }//GEN-LAST:event_OutputActionPerformed

    private void btnkonversi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkonversi3ActionPerformed
        // TODO add your handling code here:
        try{
            //rp
            if(Input.getSelectedItem()=="Rp"){
                if(Output.getSelectedItem()=="USD"){
                    double t=Double.parseDouble(teksin.getText());
                    double hasil=t*usd;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else if(Output.getSelectedItem()=="RM"){
                    double t=Double.parseDouble(teksin.getText());
                    double hasil=t*rm;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else if(Output.getSelectedItem()=="SGD"){
                    double t=Double.parseDouble(teksin.getText());
                    double hasil=t*sgd;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else if(Output.getSelectedItem()=="Euro"){
                    double t=Double.parseDouble(teksin.getText());
                    double hasil=t*euro;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else{
                    warning.showMessageDialog(null,"masukkan pilihan/angka yang benar");
                }
            }
            else if(Input.getSelectedItem()=="USD"){
                if(Output.getSelectedItem()=="Rp"){
                    double t=Double.parseDouble(teksin.getText());
                    double hasil=t/usd;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else if(Output.getSelectedItem()=="RM"){
                    double t=Double.parseDouble(teksin.getText());
                    double uang=t/usd;
                    double hasil=uang*rm;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else if(Output.getSelectedItem()=="Euro"){
                    double t=Double.parseDouble(teksin.getText());
                    double uang=t/usd;
                    double hasil=uang*euro;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else if(Output.getSelectedItem()=="SGD"){
                    double t=Double.parseDouble(teksin.getText());
                    double uang=t/usd;
                    double hasil=uang*sgd;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else{
                    warning.showMessageDialog(null,"masukkan pilihan/angka yang benar");
                }
            }
            else if(Input.getSelectedItem()=="Euro"){
                if(Output.getSelectedItem()=="Rp"){
                    double t=Double.parseDouble(teksin.getText());
                    double hasil=t/euro;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else if(Output.getSelectedItem()=="RM"){
                    double t=Double.parseDouble(teksin.getText());
                    double uang=t/euro;
                    double hasil=uang*rm;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else if(Output.getSelectedItem()=="USD"){
                    double t=Double.parseDouble(teksin.getText());
                    double uang=t/euro;
                    double hasil=uang*usd;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else if(Output.getSelectedItem()=="SGD"){
                    double t=Double.parseDouble(teksin.getText());
                    double uang=t/euro;
                    double hasil=uang*sgd;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else{
                    warning.showMessageDialog(null,"masukkan pilihan/angka yang benar");
                }
            }
            else if(Input.getSelectedItem()=="RM"){
                if(Output.getSelectedItem()=="Rp"){
                    double t=Double.parseDouble(teksin.getText());
                    double hasil=t/rm;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else if(Output.getSelectedItem()=="Euro"){
                    double t=Double.parseDouble(teksin.getText());
                    double uang=t/rm;
                    double hasil=uang*euro;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else if(Output.getSelectedItem()=="USD"){
                    double t=Double.parseDouble(teksin.getText());
                    double uang=t/rm;
                    double hasil=uang*usd;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else if(Output.getSelectedItem()=="SGD"){
                    double t=Double.parseDouble(teksin.getText());
                    double uang=t/rm;
                    double hasil=uang*sgd;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else{
                    warning.showMessageDialog(null,"masukkan pilihan/angka yang benar");
                }
            }
            else if(Input.getSelectedItem()=="SGD"){
                if(Output.getSelectedItem()=="Rp"){
                    double t=Double.parseDouble(teksin.getText());
                    double hasil=t/sgd;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else if(Output.getSelectedItem()=="RM"){
                    double t=Double.parseDouble(teksin.getText());
                    double uang=t/sgd;
                    double hasil=uang*rm;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else if(Output.getSelectedItem()=="USD"){
                    double t=Double.parseDouble(teksin.getText());
                    double uang=t/sgd;
                    double hasil=uang*usd;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else if(Output.getSelectedItem()=="Euro"){
                    double t=Double.parseDouble(teksin.getText());
                    double uang=t/sgd;
                    double hasil=uang*euro;
                    String s=d.format(hasil);
                    teksout.setText((s));
                }
                else{
                    warning.showMessageDialog(null,"masukkan pilihan/angka yang benar");
                }
            }
        }catch(NumberFormatException ex){
            warning.showMessageDialog(null,"masukkan input yang benar");
        }
    }//GEN-LAST:event_btnkonversi3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Input;
    private javax.swing.JComboBox<String> Output;
    private javax.swing.JButton btnkonversi3;
    private javax.swing.JLabel panelin;
    private javax.swing.JLabel panelout;
    private javax.swing.JLabel panelpilihan;
    private javax.swing.JTextField teksin;
    private javax.swing.JTextField teksout;
    private javax.swing.JOptionPane warning;
    // End of variables declaration//GEN-END:variables
}
